<?
if (! defined('ABSPATH')) {
    exit;
}

// Refactor: SEO meta generation logic moved to SEOService::generateSocialPostMetaTags()
// The SEOService should be instantiated and the generateSocialPostMetaTags method called
// before wp_head() to retrieve the SEO data. This data should then be used
// to output the <title>, <meta name="description">, and JSON-LD script tags.
// Example (needs to be placed appropriately in the theme's execution flow, likely functions.php or a header hook):
/*
if (is_singular('social_post')) {
    $seo_service = new SEOService();
    $seo_data = $seo_service->generateSocialPostMetaTags(get_the_ID());

    // Hook into wp_head to output the tags
    add_action('wp_head', function() use ($seo_data) {
        echo '<title>' . esc_html($seo_data['title']) . '</title>' . "\n";
        if (!empty($seo_data['description'])) {
            echo '<meta name="description" content="' . esc_attr($seo_data['description']) . '">' . "\n";
        }
        if (!empty($seo_data['schema'])) {
             echo '<script type="application/ld+json">' . wp_json_encode($seo_data['schema'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . '</script>' . "\n";
        }
        // Add Open Graph / Twitter cards if needed, potentially using $seo_data
    }, 1);
}
*/

// Note: The original code used get_the_ID() implicitly in some places.
// Ensure the context ($current_post_id) is correctly passed or retrieved if needed below.
$current_post_id = get_the_ID();
$filtro = 'single'; // This was part of the moved block, check if still needed for htmlPost
$post_title = get_the_title(); // Get title for display in the H1/H2 tags below
// $seo_title = ... ; // This is now generated by SEOService, retrieve if needed for H2

?>
<!DOCTYPE html>
<html <? language_attributes(); ?>>

<head>
    <meta charset="<? bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index, follow">
    <? wp_head(); ?>
</head>

<body <? body_class(); ?>>
    <? get_header(); ?>
    <main id="main">
        <div id="content" class="<? echo esc_attr(! is_user_logged_in() ? 'nologin' : ''); ?>">
            <? if (have_posts()) : while (have_posts()) : the_post(); ?>
                    <article <? post_class(); ?>>
                        <div style="
                            display: flex;
                            flex-direction: column;
                            align-items: center;
                            justify-content: center;
                            padding-top: 20px;
                            background: #000000;
                            margin-bottom: -20px;">
                            <h1 style="font-size: 14px;"><? echo esc_html($post_title); ?></h1>
                            <?php /* <h2 style="font-size: 12px;FONT-WEIGHT: 400;;"><? echo esc_html($seo_title); ?></h2> */ ?>
                            <?php // Note: $seo_title needs to be fetched from SEOService if you want to display it here ?>
                        </div>
                        <div class="single">
                            <div class="fullH">
                                <? echo htmlPost($filtro); ?>
                            </div>
                            <div class="publicaciones-similares" nosnippet>
                                <h3 style="display: none;">Publicaciones Similares</h3>
                                <?
                                echo publicaciones([
                                    'filtro'     => 'nada',
                                    'posts'      => 10,
                                    'similar_to' => $current_post_id,
                                ]);
                                ?>
                            </div>
                        </div>
                    </article>
            <? endwhile;
            endif; ?>
        </div>
    </main>
    <? get_footer(); ?>
</body>

</html>
