name: SonarCloud analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read
  actions: write

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.23'
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress


      # - name: Run PHPUnit tests
      #   run: |
      #     if [ -f "phpunit.xml" ]; then
      #       vendor/bin/phpunit --coverage-clover=coverage.xml
      #     else
      #       vendor/bin/phpunit --no-configuration --coverage-clover=coverage.xml
      #     fi

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=2upra_v4
            -Dsonar.organization=2upra
            -Dsonar.sources=.
            -Dsonar.php.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true
          projectBaseDir: .
